user:
    type:           rest
    resource:       BookmarkManager\ApiBundle\Controller\UserController

bookmark:
    type:           rest
    resource:       BookmarkManager\ApiBundle\Controller\BookmarkController

tag:
    type:           rest
    resource:       BookmarkManager\ApiBundle\Controller\TagController

search:
    type:           rest
    resource:       BookmarkManager\ApiBundle\Controller\SearchController


data:
    type:           rest
    resource:       BookmarkManager\ApiBundle\Controller\DataController

circle:
    type:           rest
    resource:       BookmarkManager\ApiBundle\Controller\CircleController

book:
    type:           rest
    resource:       BookmarkManager\ApiBundle\Controller\BookController

db_update_scripts:
    type:           rest
    resource:       BookmarkManager\ApiBundle\Controller\DbUpdateScriptsController