fos_rest:
    param_fetcher_listener:    force
    body_listener:             true
    allowed_methods_listener:  true
    disable_csrf_role:         ROLE_USER

    exception:
        enabled: true
        exception_controller: 'BookmarkManager\ApiBundle\Controller\ExceptionController::showAction'

    routing_loader:
        default_format:  json
        include_format:  false # Set to true to enable _format param on documentation

    format_listener:
        rules:
            - { path: '^/api', priorities: [ json ], fallback_format: json, prefer_extension: false }
            - { path: '^/oauth', priorities: [ json ], fallback_format: json, prefer_extension: false }
            - { path: '^/' }
    view:
        view_response_listener: force
        formats:
            json: true
            xml:  true

    serializer:
        serialize_null: true
