fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: api  # Seems to be used when registering user/reseting password,
                        # but since there is no "login", as so it seems to be useless in
                        # our particular context, but still required by "FOSUserBundle"
    user_class: BookmarkManager\ApiBundle\Entity\User
